### ISSUE TITLE
32 bit chimera.node missing

### ISSUE THREAD

**Issue by hxroger** [deanmao/node-chimera#3]
Hi,

Is there any chance to include 32 bit libraries?

Thanks

Roger

**Comment by deanmao** [comment]
There are 32 bit libraries in there already, when you do "npm install" it should add linux 32 bit & linux 64 bit libraries.  Mac has always been 64bit libraries.  I'm probably not going to support 32 bit PowerPC though, I don't have access to any ancient apple hardware.

**Comment by deanmao** [comment]
Oops, I'm going to redact my last comment.  I was confusing this with another library of mine....

I guess I'll look into setting up some build machines, it's tough getting so many versions of a library out :)

**Comment by hxroger** [comment]
Many thanks. Instructions on how to build the binaries would be helpful for others wanting to build it for Raspberry PI and other ARM based micro servers.

**Comment by TimNZ** [comment]
I'm not sure you should include compiled binaries and src for Qt.  Makes it harder for you to manage, as well as getting requests to support different platforms or Qt version, plus the project is now huge for downloading.

You might want to setup the gyp project to use 'standard' Qt ENV variables for include/lib paths etc, or include qmake file.  At some point you have to assume a minimum level of knowledge and expertise for a native module project, that involves Qt.

Unless you really like doing all of this. Plus there is no Windows support - come on! :)

**Comment by deanmao** [comment]
Actually the project uses a Qt library with different compile time configuration than what you'd normally find on a linux distribution.  Also, we use static libraries so that everything gets loaded into the node module.  I'm sure if we didn't include binaries, nobody would be able to figure out how to get it all working.  I'm guessing most people doing web scraping with nodejs won't have all the C++ knowledge required to understand qmake, moc, and node-gyp well enough to create their own binaries.

**Comment by deanmao** [comment]
FYI, I now have instructions for compiling your own version.  It's not for the faint of heart, but if you do manage to compile one for i386, do a pull request and I'll include your binary with the next npm package release.

**Comment by deanmao** [comment]
32bit binary is in, install it via `npm install chimera`

**Comment by TimNZ** [comment]
Is there a good reason you don't have windows support?  Like you don't have a windows machine? :)

**Comment by deanmao** [comment]
I do have a windows machine, but it's quite painful to get most open source libraries compiling on there.  If you are great at solving windows compiler errors for 3rd party libraries, feel free to give it a shot and submit a pull request for the binary.

**Comment by TimNZ** [comment]
Sure, if you are talking about Qt, generally compiles out of the box for me.  Unless you are doing some really weird compile option combos?

**Comment by deanmao** [comment]
Yes.   If you look into the source, you'll see that the configure options are very non-standard.  It stems from a number of issues:  node uses it's own openssl, which may or may not be compatible with the platform version, so we statically link it.  We also have to compile openssl with special options that allow it to be included in the future static binary.  Qt needs to use the special openssl version.  node-gyp doesn't help us here because we have a very special linker flags that include certain libraries while excluding others.

**Comment by TimNZ** [comment]
Well I think that requires someone whizzier than me.

My own QtWebKit node wrapper works just fine on win/linux and I'm using dynamic libraries.  Does it have to be static for ev support?

**Comment by deanmao** [comment]
Qt being static/dynamic doesn't matter too much, as that only influences how I would distribute the binaries.  The main thing is getting ssl in there statically.  There are some functions in openssl 0.9.8 that are different than openssl 1.0.0f that cause segfaults, so I can't rely on whatever is on the user's system.  I don't know the exact cause here as I don't know openssl that well.  The Qt options I'm using are different than usual -- most of them are actually copied straight from phantomjs's Qt build system.  

When you compile a node binary, all associated modules will be put in that statically, except for those that you choose to let the binary decide during runtime.  If you have more than one version of Qt on the system, it could pick the wrong one, unless you've modified the LD_LIBRARY_PATH or other special environment variables.  Since I'm distributing software to a bunch of people, I prefer using a static system so that I don't have to guess what the user has on their system.

It would be great if you could assist getting it to compile in windows.  I'm not a skilled windows person as I only need my windows machine for IE 7/8/9.
